export {default as GlobalLayout}  from './GlobalLayout'
export {default as YesNo}  from './YesNo'
export {default as ContactForm}  from './ContactForm'
export {default as ContactInformation}  from './ContactInformation'
export {default as RaveReviews}  from './RaveReviews'
export {default as Thumbnails}  from './Thumbnails'
export {default as Product}  from './Product'
export {default as ListItemImg}  from './ListItemImg'
export {default as BeforeAndAfter}  from './BeforeAndAfter'
export {default as SpaFndr}  from './SpaFndr'

export {default as BasicEmail} from './BasicEmail'
export {default as BasicPhone} from './BasicPhone'
export {default as Seo} from './Seo'
